# NumPy basics / cheatsheet

In [1]:
import numpy as np

## Constructing and reshaping arrays

In [2]:
np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [3]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
a = np.arange(12).reshape((4, 3))
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [5]:
a.ndim

2

In [6]:
a.shape

(4, 3)

In [7]:
len(a)

4

In [8]:
a.size

12

In [9]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

## Slicing

In [10]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [11]:
a[1:-1, 1:-1]

array([[4],
       [7]])

## Arithmetic operations

In [12]:
b = a.copy()

In [13]:
a + b

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22]])

In [14]:
a * b

array([[  0,   1,   4],
       [  9,  16,  25],
       [ 36,  49,  64],
       [ 81, 100, 121]])

In [15]:
a @ b

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 3)

In [16]:
a @ b.T

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

## Combining arrays

In [17]:
np.concatenate([a, b], axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [18]:
c = np.stack([a, b], axis=-1)
c

array([[[ 0,  0],
        [ 1,  1],
        [ 2,  2]],

       [[ 3,  3],
        [ 4,  4],
        [ 5,  5]],

       [[ 6,  6],
        [ 7,  7],
        [ 8,  8]],

       [[ 9,  9],
        [10, 10],
        [11, 11]]])

In [19]:
c.shape

(4, 3, 2)

## Aggregations & axes

In [20]:
c.sum(axis=2)

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22]])

## Broadcasting

![Broadcasting](images/broadcasting.png)

Rules of broadcasting:

1. If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side.
2. If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.
3. If in any dimension the sizes disagree and neither is equal to 1, an error is raised.

Source: https://jakevdp.github.io/PythonDataScienceHandbook/02.05-computation-on-arrays-broadcasting.html

In [22]:
a + 1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [23]:
a + [1]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [24]:
a + [0, 1, 2]

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10],
       [ 9, 11, 13]])

In [58]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [113]:
x = np.arange(3)
y = np.arange(3)[:, np.newaxis]

print(x)
print(y)

[0 1 2]
[[0]
 [1]
 [2]]


In [114]:
x + y

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])